"""new fields in user model

Revision ID: 214878006fb8
Revises: afc2d6e34370
Create Date: 2020-06-03 08:47:31.863699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '214878006fb8'
down_revision = 'afc2d6e34370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
